name: nok_test

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  auto_route: ^5.0.4

  injectable: ^2.1.1
  get_it: ^7.2.0
  firebase_core: ^2.10.0
  firebase_database: ^10.1.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  auto_route_generator: ^5.0.3
  injectable_generator: ^2.1.5

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/