name: nok_test

publish_to: 'none'

version: 1.4.0+12

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  auto_route: ^9.2.2

  injectable: ^2.1.1
  get_it: ^8.0.2
  firebase_core: ^2.32.0
  firebase_database: ^10.5.7
  flutter_launcher_icons: ^0.14.1
  package_info_plus: ^8.0.2
  open_store: ^0.5.0
  firebase_auth: ^4.16.0
  retrofit: '>=4.0.0 <5.0.0'
  dio: ^5.4.2+1
  bloc_concurrency: ^0.2.5
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.16
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.1.5
  retrofit_generator: ^9.1.4
  test: ^1.24.9
  bloc_test: ^9.1.7

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/